name: CI (Pull Request checks)

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - run: npm install

      - name: Run ESLint & Compile Typescript
        run: npm run lint

  test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - run: npm install
      - run: npm run test:ci


  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - run: npm install
      - name: Build the app
        run: npm run build